---
repos:
  vcsh:
    - name: mr_public
      desc: MyRepos main dotfiles configuration
      remote:
        https: https://framagit.org/rdeville.public/my_dotfiles/myrepo.git
        ssh: git@framagit.org:rdeville.public/my_dotfiles/myrepo.git
      command:
        post_clone:
          - git flow init -d
