---
# MKDocs configuration
# https://www.mkdocs.org/
# =============================================================================
# Configuraiton file describing the documentation using mkdocs.

# IMPORTANT: This file is not to be used to render documentation locally as it
# is included in the main documentation.
# Use `mkdocs serve -f mkdocs.local.yml` for the local rendering

# Website Information
# ---------------------------------------------------------------------------
site_name: my_dotfiles/myrepos

# Website architecture
# ---------------------------------------------------------------------------
nav:
  - Home: index.md
  - Usage:
    - VCSH: usage/vcsh.md
    - MyRepos: usage/myrepos.md
    - Setup myrepos configuration: usage/setup_myrepos_configuration.md
    - Keep your own configuration: usage/keep_your_configuration.md
  - About:
    - Appendix: about/appendix.md
    - Release Notes: about/release_notes.md
    - FAQ: about/FAQ.md
    - License: about/license.md
    - Code of conduct: about/code_of_conduct.md

# *****************************************************************************
# EDITOR CONFIG
# vim: ft=yaml: ts=2: sw=2: sts=2
# *****************************************************************************
